-- USE master
-- GO
-- DROP DATABASE Clinica

CREATE DATABASE Clinica
go
USE Clinica
go

CREATE TABLE PERFIL (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    NOMBRE VARCHAR(50) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT(1)
)
GO


CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    PASS VARCHAR(50) NOT NULL,
    IDPERFIL INT NOT NULL FOREIGN KEY REFERENCES PERFIL(ID),
    ACTIVO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE PERSONA (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),    
    APELLIDO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO SMALLDATETIME NOT NULL,
    DNI INT NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    IDUSUARIO INT NULL FOREIGN KEY REFERENCES USUARIO(ID),
    ACTIVO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE ESPECIALIDAD (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    NOMBRE VARCHAR(50) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE HORARIO (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    HORA_DESDE INT NOT NULL CHECK ( HORA_DESDE >= 0 AND HORA_DESDE <= 23 ),
    HORA_HASTA INT NOT NULL CHECK ( HORA_HASTA >= 0 AND HORA_HASTA <= 23 ),
    DIA INT NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT(1)
)


CREATE TABLE MEDICO (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    MATRICULA VARCHAR(50) NOT NULL,
    IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONA(ID)
)
GO

CREATE TABLE MEDICO_X_HORARIO (
    IDMEDICO INT,
	IDHORARIO INT,
	PRIMARY KEY (IDMEDICO, IDHORARIO),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (ID),
	FOREIGN KEY (IDHORARIO) REFERENCES HORARIO (ID)
)
GO

CREATE TABLE MEDICO_X_ESPECIALIDAD (
    IDMEDICO INT,
	IDESPECIALIDAD INT,
	PRIMARY KEY (IDMEDICO, IDESPECIALIDAD),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (ID),
	FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDAD (ID)
)
GO

CREATE TABLE TURNO_ESTADO (
    ID INT NOT NULL PRIMARY KEY, 
    NOMBRE VARCHAR(50) NOT NULL, 
    ACTIVO INT NOT NULL DEFAULT(1) 
)
GO

CREATE TABLE OBRASOCIAL (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    NOMBRE VARCHAR(50) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    CUIT VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    ACTIVO BIT NOT NULL DEFAULT(1)
)
GO

CREATE TABLE PACIENTE (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONA(ID),
    IDOBRASOCIAL INT NOT NULL FOREIGN KEY REFERENCES OBRASOCIAL(ID),
    PESO DECIMAL NOT NULL CHECK ( PESO > 0),
    ALTURA DECIMAL NOT NULL CHECK ( ALTURA > 0),
    CREDENCIAL VARCHAR(50) NOT NULL
)
GO

CREATE TABLE TURNO (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    IDPACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTE(ID),
    IDESPECIALIDAD INT NOT NULL,
    FECHA_SOLICITADO SMALLDATETIME NOT NULL,
    FECHA SMALLDATETIME NOT NULL,
    HORA TINYINT NOT NULL CHECK ( HORA >= 0 AND HORA <= 23 ),
    IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICO(ID),
    OBSERVACIONES VARCHAR(250) NULL,
    ESTADO INT NOT NULL DEFAULT(0) FOREIGN KEY REFERENCES TURNO_ESTADO(ID)
)
GO