/* ESPECIALIDADES */
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('MÉDICO CLÍNICO')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('CARDIOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('PEDIATRÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ENDOCRINOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ODONTOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUMOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NUTRICIÓN')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('OFTALMOLOGÍA')

