SET DATEFORMAT dmy;
GO
USE Clinica
GO

/* DBCC CHECKIDENT (HORARIO, RESEED, 0)   PARA REINICIAR EL IDENTITY DE ALGUNA TABLA*/

/* ESPECIALIDADES ---- SELECT * FROM ESPECIALIDAD */
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('MÉDICO CLÍNICO')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('CARDIOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('PEDIATRÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ENDOCRINOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ODONTOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUMOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NUTRICIÓN')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('OFTALMOLOGÍA')

/*COBERTURAS (OBRA SOCIAL, PREPAGAS, ART) ---- SELECT * FROM OBRASOCIAL */
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Organizacion de Servicios Directos Empresarios','OSDE',318756123,435869,'AV Avenida 123','Osde@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('MEDICUS','MEDICUS',31987644,499879,'Calle x 321','Medicus@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('GALENO','GALENO',309784552,405891,'La Calle 8','Galeno@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Obra Social de Empleados de Comercio','OSECAC',32888994,397851,'Dorado oscuro 454','Osecac@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Instituto de Obra Medico Asitencial','IOMA',30879456,486969,'Otra calle 13','IOMA@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Programa Asistencia Medica Integral','PAMI',30123123,456123,'Calle vieja 95','PAMI@algo.com')

/* PERFILES ---- SELECT * FROM PERFIL */
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Administrador')
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Médico')
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Recepcionista')

/* USUARIOS  ---- SELECT * FROM USUARIO */
INSERT INTO USUARIO ( PASS ) VALUES ('1234')
INSERT INTO USUARIO ( PASS ) VALUES ('1234')
INSERT INTO USUARIO ( PASS ) VALUES ('1234')
INSERT INTO USUARIO ( PASS ) VALUES ('1234')

/* USUARIOS_X_PERFILES ---- SELECT * FROM USUARIO_X_PERFILES */
INSERT INTO USUARIO_X_PERFILES ( IDUSUARIO, IDPERFIL ) VALUES (1,1) -- Usuario 1 es Administrador
INSERT INTO USUARIO_X_PERFILES ( IDUSUARIO, IDPERFIL ) VALUES (2,2) -- Usuario 2 es Médico
INSERT INTO USUARIO_X_PERFILES ( IDUSUARIO, IDPERFIL ) VALUES (3,2) -- Usuario 3 es Médico
INSERT INTO USUARIO_X_PERFILES ( IDUSUARIO, IDPERFIL ) VALUES (4,3) -- Usuario 4 es Recepcionista


/* HORARIO MEDICOS ---- SELECT * FROM HORARIO */
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 1)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 2)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 3)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 4)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 5)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 6)

/* PERSONA ---- SELECT * FROM PERSONA */
INSERT INTO PERSONA (APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO) VALUES ( 'Goncalves', 'Camila ', '23/10/1996','43431806','cami.goncalves@clinic.com', 1 )
INSERT INTO PERSONA (APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO) VALUES ( 'Socolinsky', 'Mario', '12/07/1942','10231567','mario.soco.doc@clinic.com', 2 )
INSERT INTO PERSONA (APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO) VALUES ( 'Cormillot', 'Alberto ', '31/08/1938','10198762','alberto.cormi.doc@clinic.com', 3 )
INSERT INTO PERSONA (APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO) VALUES ( 'Gines', 'Sebastián ', '13/01/1987','33876312','sebastian.gines@clinic.com', 4 )


/* MEDICOS ---- SELECT * FROM MEDICO */
INSERT INTO MEDICO ( MATRICULA, IDPERSONA) VALUES ('231441', 2)
INSERT INTO MEDICO ( MATRICULA, IDPERSONA) VALUES ('231441', 3)

/* MEDICOS X HORARIOS ----- SELECT * FROM MEDICO_X_HORARIO */
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (1,1)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (1,2)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (1,5)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,1)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,2)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,3)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,4)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,5)
INSERT INTO MEDICO_X_HORARIO (IDMEDICO, IDHORARIO) VALUES (2,6)

