/* ESPECIALIDADES */
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('MÉDICO CLÍNICO')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('CARDIOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('GASTROENTEROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('PEDIATRÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ENDOCRINOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ODONTOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUROLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUMOLOGÍA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NUTRICIÓN')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('OFTALMOLOGÍA')

/*COBERTURAS (OBRA SOCIAL, PREPAGAS, ART)*/
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Organizacion de Servicios Directos Empresarios','OSDE',318756123,435869,'AV Avenida 123','Osde@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('MEDICUS','MEDICUS',31987644,499879,'Calle x 321','Medicus@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('GALENO','GALENO',309784552,405891,'La Calle 8','Galeno@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Obra Social de Empleados de Comercio','OSECAC',32888994,397851,'Dorado oscuro 454','Osecac@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Instituto de Obra Medico Asitencial','IOMA',30879456,486969,'Otra calle 13','IOMA@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Programa Asistencia Medica Integral','PAMI',30123123,456123,'Calle vieja 95','PAMI@algo.com')

