SET DATEFORMAT dmy;
GO
USE Clinica
GO

/* DBCC CHECKIDENT (HORARIO, RESEED, 0)   PARA REINICIAR EL IDENTITY DE ALGUNA TABLA*/

/* ESPECIALIDADES ---- SELECT * FROM ESPECIALIDAD */
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('MEDICO CLINICO')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('CARDIOLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('GASTROENTEROLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('PEDIATRIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ENDOCRINOLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('ODONTOLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUROLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NEUMOLOGIA')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('NUTRICION')
INSERT INTO ESPECIALIDAD ( NOMBRE) VALUES ('OFTALMOLOGIA')

/*COBERTURAS (OBRA SOCIAL, PREPAGAS, ART) ---- SELECT * FROM OBRASOCIAL */
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Organizacion de Servicios Directos Empresarios','OSDE',318756123,435869,'AV Avenida 123','Osde@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('MEDICUS','MEDICUS',31987644,499879,'Calle x 321','Medicus@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('GALENO','GALENO',309784552,405891,'La Calle 8','Galeno@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Obra Social de Empleados de Comercio','OSECAC',32888994,397851,'Dorado oscuro 454','Osecac@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Instituto de Obra Medico Asitencial','IOMA',30879456,486969,'Otra calle 13','IOMA@algo.com')
INSERT INTO OBRASOCIAL ( NOMBRE,SIGLA,CUIT,TELEFONO,DIRECCION,MAIL ) VALUES ('Programa Asistencia Medica Integral','PAMI',30123123,456123,'Calle vieja 95','PAMI@algo.com')

/* PERFILES ---- SELECT * FROM PERFIL */
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Administrador')
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Medico')
INSERT INTO PERFIL ( NOMBRE ) VALUES ('Recepcionista')

/* USUARIOS  ---- SELECT * FROM USUARIO */
INSERT INTO USUARIO ( PASS, IDPERFIL ) VALUES ('1234',1)
INSERT INTO USUARIO ( PASS, IDPERFIL ) VALUES ('1234',2)
INSERT INTO USUARIO ( PASS, IDPERFIL ) VALUES ('1234',2)
INSERT INTO USUARIO ( PASS, IDPERFIL ) VALUES ('1234',3)

/* USUARIOS  ---- SELECT * FROM PERSONAL */
INSERT INTO PERSONA(APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO ) VALUES ('Goncalves', 'Camila ', '23/10/1996',39986313,'cami.goncalves@clinic.com',1)
INSERT INTO PERSONA(APELLIDO, NOMBRE, FECHA_NACIMIENTO, DNI, MAIL, IDUSUARIO ) VALUES ('Gines', 'Sebastian ', '13/01/1987',33876312,'sebastian.gines@gmail.com',1)


/* HORARIO MEDICOS ---- SELECT * FROM HORARIO */
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 1)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 2)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 3)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 4)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 5)
INSERT INTO HORARIO (HORA_DESDE, HORA_HASTA, DIA) VALUES (8, 16, 6)


/* PERSONA ---- SELECT * FROM MEDICO */ 
EXEC SP_AltaMedico  'Socolinsky', 'Mario', '12/07/1942','10231567','mario.soco.doc@clinic.com', '231441','1,2,','1,2,3,4,5,','1234'
EXEC SP_AltaMedico  'Cormillot', 'Alberto ', '31/08/1938','10198762','alberto.cormi.doc@clinic.com', '231441','1,2,','1,2,3,4,5,','1234'

/* PACIENTE ---- SELECT * FROM PACIENTE */ 
EXEC SP_AltaPaciente 'Argento','Pepe', '15/08/1960', 16234111, 'pepe@gmail.com', '23213123', 1, 80, '190'
EXEC SP_AltaPaciente 'Argento','Moni', '07/01/1970', 16234111, 'moni@gmail.com', '23213123', 1, 80, '180'
EXEC SP_AltaPaciente 'Constantes','Dolores', '20/10/1992', 16234111, 'dolores@gmail.com', '23213123', 1, 80, '170'
EXEC SP_AltaPaciente 'Tomando', 'Remedios','05/04/1986', 16234111, 'remedios@gmail.com', '23113123', 1, 80, '160'
EXEC SP_AltaPaciente 'Goncalves', 'Denise', '23/10/1996', 16234111, 'camiladenise.96@gmail.com','23113123',1,80,'150'


/* PACIENTE ---- SELECT * FROM TURNO_ESTADO */ 
INSERT INTO TURNO_ESTADO (ID,NOMBRE) VALUES (1, 'Nuevo')
INSERT INTO TURNO_ESTADO (ID,NOMBRE) VALUES (2, 'Cerrado')
INSERT INTO TURNO_ESTADO (ID,NOMBRE) VALUES (3, 'Cancelado')


/* PACIENTE ---- SELECT * FROM TURNO */ 
INSERT INTO TURNO (IDPACIENTE,IDESPECIALIDAD,FECHA_SOLICITADO,FECHA,HORA,IDMEDICO,OBSERVACIONES,ESTADO) VALUES (1,1,'26/11/2022','23/12/2022', 1, 1,'',1)



